# Configuration file for GNN training

precision: float32  # 或 float16

paths:
  pattern_paths:
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_label_range_6/q1.pt"
      # - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_label_range_6/q2.pt"
      #- "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_label_range_6/q3.pt"
      #- "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_label_range_6/q4.pt"
      #- "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_label_range_6/q10.pt"
  graph_path: 
     "/data/zhuxiaoke/workspace/Torch/pt/pokec.pt"
  gt_paths:
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_label_range_6/q1.gt"
      #    - "/data/zhuxiaoke/workspace/Torch/gt/1000_label_range_6/q2.gt"
      #    - "/data/zhuxiaoke/workspace/Torch/gt/1000_label_range_6/q3.gt"
      #    - "/data/zhuxiaoke/workspace/Torch/gt/1000_label_range_6/q4.gt"
      #    - "/data/zhuxiaoke/workspace/Torch/gt/1000_label_range_6/q10.gt"
  output_dir: "/data/zhuxiaoke/workspace/Torch/models/1000_label_range_6/pokec_label_range_6/"

model:
  in_channels: 64 # default 16
  hidden_channels: 64 # default 64
  out_channels: 64 # default 64

mlp_model:
  hidden_channels: 16 # default 8

similarity_generator:
  embedding_size: 64 # default 64
  similarity_method: "euclidean"
  normalize: true
  combination_weights: [ 0.8, 0.1, 0.1 ]

training:
  learning_rate: 0.00003
  epochs: 10000

test_vertex_id: 0
