# Configuration file for GNN training

precision: float32  # 或 float16

paths:
  pattern_paths:
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q100.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q200.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q300.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q400.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q500.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q600.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q700.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q800.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q900.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q150.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q250.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q350.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q450.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q550.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q650.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q750.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q850.pt"
    - "/data/zhuxiaoke/workspace/Torch/pt/queries/1000_2/q950.pt"
  graph_path: "/data/zhuxiaoke/workspace/Torch/pt/pokec_label_range_50.pt"
  gt_paths:
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q100.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q200.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q300.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q400.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q500.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q600.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q700.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q800.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q900.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q150.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q250.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q350.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q450.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q550.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q650.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q750.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q850.gt"
    - "/data/zhuxiaoke/workspace/Torch/gt/1000_2/pokec_q950.gt"
  output_dir: "/data/zhuxiaoke/workspace/Torch/models/1000_2/pokec_label_range_6/"

model:
  in_channels: 64 # default 16
  hidden_channels: 64 # default 64
  out_channels: 64 # default 64

mlp_model:
  hidden_channels: 16 # default 8

similarity_generator:
  embedding_size: 64 # default 64
  similarity_method: "euclidean"
  normalize: true
  combination_weights: [ 0.8, 0.1, 0.1 ]

training:
  learning_rate: 0.001
  epochs: 1000

test_vertex_id: 590
